export {Component} from "./component";
export {_Register} from "./register";
export {FactoryForm} from "./factoryForm";
export {Circle} from "./entities/circle";
export {Point} from "./maths/point";
export {_uuid} from "./maths/uuid";
export {Rectangle} from "./entities/rectangle";
export {Connector} from "./entities/connector";
export {Line} from "./entities/line";
export {events} from "./events";
// export {events} from "../tests/test_app.js";
